/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LoginTwitterRouteImport } from './routes/login.twitter'
import { Route as LoginGoogleRouteImport } from './routes/login.google'
import { Route as LoginFacebookRouteImport } from './routes/login.facebook'
import { Route as LocaleProfileRouteImport } from './routes/$locale.profile'
import { Route as LocaleDashboardRouteImport } from './routes/$locale.dashboard'
import { Route as LoginTwitterCallbackRouteImport } from './routes/login.twitter.callback'
import { Route as LoginGoogleCallbackRouteImport } from './routes/login.google.callback'
import { Route as LoginFacebookCallbackRouteImport } from './routes/login.facebook.callback'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LoginTwitterRoute = LoginTwitterRouteImport.update({
  id: '/login/twitter',
  path: '/login/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginGoogleRoute = LoginGoogleRouteImport.update({
  id: '/login/google',
  path: '/login/google',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFacebookRoute = LoginFacebookRouteImport.update({
  id: '/login/facebook',
  path: '/login/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProfileRoute = LocaleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDashboardRoute = LocaleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleRoute,
} as any)
const LoginTwitterCallbackRoute = LoginTwitterCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginTwitterRoute,
} as any)
const LoginGoogleCallbackRoute = LoginGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginGoogleRoute,
} as any)
const LoginFacebookCallbackRoute = LoginFacebookCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginFacebookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/profile': typeof LocaleProfileRoute
  '/login/facebook': typeof LoginFacebookRouteWithChildren
  '/login/google': typeof LoginGoogleRouteWithChildren
  '/login/twitter': typeof LoginTwitterRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/login/facebook/callback': typeof LoginFacebookCallbackRoute
  '/login/google/callback': typeof LoginGoogleCallbackRoute
  '/login/twitter/callback': typeof LoginTwitterCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/profile': typeof LocaleProfileRoute
  '/login/facebook': typeof LoginFacebookRouteWithChildren
  '/login/google': typeof LoginGoogleRouteWithChildren
  '/login/twitter': typeof LoginTwitterRouteWithChildren
  '/$locale': typeof LocaleIndexRoute
  '/login/facebook/callback': typeof LoginFacebookCallbackRoute
  '/login/google/callback': typeof LoginGoogleCallbackRoute
  '/login/twitter/callback': typeof LoginTwitterCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/profile': typeof LocaleProfileRoute
  '/login/facebook': typeof LoginFacebookRouteWithChildren
  '/login/google': typeof LoginGoogleRouteWithChildren
  '/login/twitter': typeof LoginTwitterRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/login/facebook/callback': typeof LoginFacebookCallbackRoute
  '/login/google/callback': typeof LoginGoogleCallbackRoute
  '/login/twitter/callback': typeof LoginTwitterCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/dashboard'
    | '/$locale/profile'
    | '/login/facebook'
    | '/login/google'
    | '/login/twitter'
    | '/$locale/'
    | '/login/facebook/callback'
    | '/login/google/callback'
    | '/login/twitter/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/dashboard'
    | '/$locale/profile'
    | '/login/facebook'
    | '/login/google'
    | '/login/twitter'
    | '/$locale'
    | '/login/facebook/callback'
    | '/login/google/callback'
    | '/login/twitter/callback'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/dashboard'
    | '/$locale/profile'
    | '/login/facebook'
    | '/login/google'
    | '/login/twitter'
    | '/$locale/'
    | '/login/facebook/callback'
    | '/login/google/callback'
    | '/login/twitter/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  LoginFacebookRoute: typeof LoginFacebookRouteWithChildren
  LoginGoogleRoute: typeof LoginGoogleRouteWithChildren
  LoginTwitterRoute: typeof LoginTwitterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/login/twitter': {
      id: '/login/twitter'
      path: '/login/twitter'
      fullPath: '/login/twitter'
      preLoaderRoute: typeof LoginTwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/google': {
      id: '/login/google'
      path: '/login/google'
      fullPath: '/login/google'
      preLoaderRoute: typeof LoginGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/facebook': {
      id: '/login/facebook'
      path: '/login/facebook'
      fullPath: '/login/facebook'
      preLoaderRoute: typeof LoginFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/profile': {
      id: '/$locale/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleProfileRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dashboard': {
      id: '/$locale/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleDashboardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/login/twitter/callback': {
      id: '/login/twitter/callback'
      path: '/callback'
      fullPath: '/login/twitter/callback'
      preLoaderRoute: typeof LoginTwitterCallbackRouteImport
      parentRoute: typeof LoginTwitterRoute
    }
    '/login/google/callback': {
      id: '/login/google/callback'
      path: '/callback'
      fullPath: '/login/google/callback'
      preLoaderRoute: typeof LoginGoogleCallbackRouteImport
      parentRoute: typeof LoginGoogleRoute
    }
    '/login/facebook/callback': {
      id: '/login/facebook/callback'
      path: '/callback'
      fullPath: '/login/facebook/callback'
      preLoaderRoute: typeof LoginFacebookCallbackRouteImport
      parentRoute: typeof LoginFacebookRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleDashboardRoute: typeof LocaleDashboardRoute
  LocaleProfileRoute: typeof LocaleProfileRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleDashboardRoute: LocaleDashboardRoute,
  LocaleProfileRoute: LocaleProfileRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface LoginFacebookRouteChildren {
  LoginFacebookCallbackRoute: typeof LoginFacebookCallbackRoute
}

const LoginFacebookRouteChildren: LoginFacebookRouteChildren = {
  LoginFacebookCallbackRoute: LoginFacebookCallbackRoute,
}

const LoginFacebookRouteWithChildren = LoginFacebookRoute._addFileChildren(
  LoginFacebookRouteChildren,
)

interface LoginGoogleRouteChildren {
  LoginGoogleCallbackRoute: typeof LoginGoogleCallbackRoute
}

const LoginGoogleRouteChildren: LoginGoogleRouteChildren = {
  LoginGoogleCallbackRoute: LoginGoogleCallbackRoute,
}

const LoginGoogleRouteWithChildren = LoginGoogleRoute._addFileChildren(
  LoginGoogleRouteChildren,
)

interface LoginTwitterRouteChildren {
  LoginTwitterCallbackRoute: typeof LoginTwitterCallbackRoute
}

const LoginTwitterRouteChildren: LoginTwitterRouteChildren = {
  LoginTwitterCallbackRoute: LoginTwitterCallbackRoute,
}

const LoginTwitterRouteWithChildren = LoginTwitterRoute._addFileChildren(
  LoginTwitterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  LoginFacebookRoute: LoginFacebookRouteWithChildren,
  LoginGoogleRoute: LoginGoogleRouteWithChildren,
  LoginTwitterRoute: LoginTwitterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
