/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LoginTwitterRouteImport } from './routes/login.twitter'
import { Route as LoginGoogleRouteImport } from './routes/login.google'
import { Route as LoginFacebookRouteImport } from './routes/login.facebook'
import { Route as LocaleTestimoniesRouteImport } from './routes/$locale.testimonies'
import { Route as LocaleRoadmapRouteImport } from './routes/$locale.roadmap'
import { Route as LocaleProfileRouteImport } from './routes/$locale.profile'
import { Route as LocaleEventsRouteImport } from './routes/$locale.events'
import { Route as LocaleDashboardRouteImport } from './routes/$locale.dashboard'
import { Route as LocaleAdminRouteImport } from './routes/$locale.admin'
import { Route as LoginTwitterCallbackRouteImport } from './routes/login.twitter.callback'
import { Route as LoginGoogleCallbackRouteImport } from './routes/login.google.callback'
import { Route as LoginFacebookCallbackRouteImport } from './routes/login.facebook.callback'
import { Route as LocaleTestimoniesCreateRouteImport } from './routes/$locale.testimonies.create'
import { Route as LocaleEventsCreateRouteImport } from './routes/$locale.events.create'
import { Route as LocaleAdminUsersRouteImport } from './routes/$locale.admin.users'
import { Route as LocaleAdminTranslationsRouteImport } from './routes/$locale.admin.translations'
import { Route as LocaleAdminRecommendationsRouteImport } from './routes/$locale.admin.recommendations'
import { Route as LocaleAdminModerationRouteImport } from './routes/$locale.admin.moderation'
import { Route as LocaleAdminFeedbackRouteImport } from './routes/$locale.admin.feedback'
import { Route as LocaleAdminCoursesRouteImport } from './routes/$locale.admin.courses'
import { Route as LocaleTestimoniesIdIndexRouteImport } from './routes/$locale.testimonies.$id.index'
import { Route as LocaleEventsIdIndexRouteImport } from './routes/$locale.events.$id.index'
import { Route as LocaleTestimoniesIdEditRouteImport } from './routes/$locale.testimonies.$id.edit'
import { Route as LocaleEventsIdEditRouteImport } from './routes/$locale.events.$id.edit'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LoginTwitterRoute = LoginTwitterRouteImport.update({
  id: '/login/twitter',
  path: '/login/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginGoogleRoute = LoginGoogleRouteImport.update({
  id: '/login/google',
  path: '/login/google',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFacebookRoute = LoginFacebookRouteImport.update({
  id: '/login/facebook',
  path: '/login/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTestimoniesRoute = LocaleTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRoadmapRoute = LocaleRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProfileRoute = LocaleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEventsRoute = LocaleEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDashboardRoute = LocaleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LoginTwitterCallbackRoute = LoginTwitterCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginTwitterRoute,
} as any)
const LoginGoogleCallbackRoute = LoginGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginGoogleRoute,
} as any)
const LoginFacebookCallbackRoute = LoginFacebookCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginFacebookRoute,
} as any)
const LocaleTestimoniesCreateRoute = LocaleTestimoniesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LocaleTestimoniesRoute,
} as any)
const LocaleEventsCreateRoute = LocaleEventsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LocaleEventsRoute,
} as any)
const LocaleAdminUsersRoute = LocaleAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminTranslationsRoute = LocaleAdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminRecommendationsRoute =
  LocaleAdminRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => LocaleAdminRoute,
  } as any)
const LocaleAdminModerationRoute = LocaleAdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminFeedbackRoute = LocaleAdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminCoursesRoute = LocaleAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleTestimoniesIdIndexRoute =
  LocaleTestimoniesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => LocaleTestimoniesRoute,
  } as any)
const LocaleEventsIdIndexRoute = LocaleEventsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => LocaleEventsRoute,
} as any)
const LocaleTestimoniesIdEditRoute = LocaleTestimoniesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => LocaleTestimoniesRoute,
} as any)
const LocaleEventsIdEditRoute = LocaleEventsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => LocaleEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/events': typeof LocaleEventsRouteWithChildren
  '/$locale/profile': typeof LocaleProfileRoute
  '/$locale/roadmap': typeof LocaleRoadmapRoute
  '/$locale/testimonies': typeof LocaleTestimoniesRouteWithChildren
  '/login/facebook': typeof LoginFacebookRouteWithChildren
  '/login/google': typeof LoginGoogleRouteWithChildren
  '/login/twitter': typeof LoginTwitterRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/courses': typeof LocaleAdminCoursesRoute
  '/$locale/admin/feedback': typeof LocaleAdminFeedbackRoute
  '/$locale/admin/moderation': typeof LocaleAdminModerationRoute
  '/$locale/admin/recommendations': typeof LocaleAdminRecommendationsRoute
  '/$locale/admin/translations': typeof LocaleAdminTranslationsRoute
  '/$locale/admin/users': typeof LocaleAdminUsersRoute
  '/$locale/events/create': typeof LocaleEventsCreateRoute
  '/$locale/testimonies/create': typeof LocaleTestimoniesCreateRoute
  '/login/facebook/callback': typeof LoginFacebookCallbackRoute
  '/login/google/callback': typeof LoginGoogleCallbackRoute
  '/login/twitter/callback': typeof LoginTwitterCallbackRoute
  '/$locale/events/$id/edit': typeof LocaleEventsIdEditRoute
  '/$locale/testimonies/$id/edit': typeof LocaleTestimoniesIdEditRoute
  '/$locale/events/$id/': typeof LocaleEventsIdIndexRoute
  '/$locale/testimonies/$id/': typeof LocaleTestimoniesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/events': typeof LocaleEventsRouteWithChildren
  '/$locale/profile': typeof LocaleProfileRoute
  '/$locale/roadmap': typeof LocaleRoadmapRoute
  '/$locale/testimonies': typeof LocaleTestimoniesRouteWithChildren
  '/login/facebook': typeof LoginFacebookRouteWithChildren
  '/login/google': typeof LoginGoogleRouteWithChildren
  '/login/twitter': typeof LoginTwitterRouteWithChildren
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/courses': typeof LocaleAdminCoursesRoute
  '/$locale/admin/feedback': typeof LocaleAdminFeedbackRoute
  '/$locale/admin/moderation': typeof LocaleAdminModerationRoute
  '/$locale/admin/recommendations': typeof LocaleAdminRecommendationsRoute
  '/$locale/admin/translations': typeof LocaleAdminTranslationsRoute
  '/$locale/admin/users': typeof LocaleAdminUsersRoute
  '/$locale/events/create': typeof LocaleEventsCreateRoute
  '/$locale/testimonies/create': typeof LocaleTestimoniesCreateRoute
  '/login/facebook/callback': typeof LoginFacebookCallbackRoute
  '/login/google/callback': typeof LoginGoogleCallbackRoute
  '/login/twitter/callback': typeof LoginTwitterCallbackRoute
  '/$locale/events/$id/edit': typeof LocaleEventsIdEditRoute
  '/$locale/testimonies/$id/edit': typeof LocaleTestimoniesIdEditRoute
  '/$locale/events/$id': typeof LocaleEventsIdIndexRoute
  '/$locale/testimonies/$id': typeof LocaleTestimoniesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/events': typeof LocaleEventsRouteWithChildren
  '/$locale/profile': typeof LocaleProfileRoute
  '/$locale/roadmap': typeof LocaleRoadmapRoute
  '/$locale/testimonies': typeof LocaleTestimoniesRouteWithChildren
  '/login/facebook': typeof LoginFacebookRouteWithChildren
  '/login/google': typeof LoginGoogleRouteWithChildren
  '/login/twitter': typeof LoginTwitterRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/courses': typeof LocaleAdminCoursesRoute
  '/$locale/admin/feedback': typeof LocaleAdminFeedbackRoute
  '/$locale/admin/moderation': typeof LocaleAdminModerationRoute
  '/$locale/admin/recommendations': typeof LocaleAdminRecommendationsRoute
  '/$locale/admin/translations': typeof LocaleAdminTranslationsRoute
  '/$locale/admin/users': typeof LocaleAdminUsersRoute
  '/$locale/events/create': typeof LocaleEventsCreateRoute
  '/$locale/testimonies/create': typeof LocaleTestimoniesCreateRoute
  '/login/facebook/callback': typeof LoginFacebookCallbackRoute
  '/login/google/callback': typeof LoginGoogleCallbackRoute
  '/login/twitter/callback': typeof LoginTwitterCallbackRoute
  '/$locale/events/$id/edit': typeof LocaleEventsIdEditRoute
  '/$locale/testimonies/$id/edit': typeof LocaleTestimoniesIdEditRoute
  '/$locale/events/$id/': typeof LocaleEventsIdIndexRoute
  '/$locale/testimonies/$id/': typeof LocaleTestimoniesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/dashboard'
    | '/$locale/events'
    | '/$locale/profile'
    | '/$locale/roadmap'
    | '/$locale/testimonies'
    | '/login/facebook'
    | '/login/google'
    | '/login/twitter'
    | '/$locale/'
    | '/$locale/admin/courses'
    | '/$locale/admin/feedback'
    | '/$locale/admin/moderation'
    | '/$locale/admin/recommendations'
    | '/$locale/admin/translations'
    | '/$locale/admin/users'
    | '/$locale/events/create'
    | '/$locale/testimonies/create'
    | '/login/facebook/callback'
    | '/login/google/callback'
    | '/login/twitter/callback'
    | '/$locale/events/$id/edit'
    | '/$locale/testimonies/$id/edit'
    | '/$locale/events/$id/'
    | '/$locale/testimonies/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/admin'
    | '/$locale/dashboard'
    | '/$locale/events'
    | '/$locale/profile'
    | '/$locale/roadmap'
    | '/$locale/testimonies'
    | '/login/facebook'
    | '/login/google'
    | '/login/twitter'
    | '/$locale'
    | '/$locale/admin/courses'
    | '/$locale/admin/feedback'
    | '/$locale/admin/moderation'
    | '/$locale/admin/recommendations'
    | '/$locale/admin/translations'
    | '/$locale/admin/users'
    | '/$locale/events/create'
    | '/$locale/testimonies/create'
    | '/login/facebook/callback'
    | '/login/google/callback'
    | '/login/twitter/callback'
    | '/$locale/events/$id/edit'
    | '/$locale/testimonies/$id/edit'
    | '/$locale/events/$id'
    | '/$locale/testimonies/$id'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/dashboard'
    | '/$locale/events'
    | '/$locale/profile'
    | '/$locale/roadmap'
    | '/$locale/testimonies'
    | '/login/facebook'
    | '/login/google'
    | '/login/twitter'
    | '/$locale/'
    | '/$locale/admin/courses'
    | '/$locale/admin/feedback'
    | '/$locale/admin/moderation'
    | '/$locale/admin/recommendations'
    | '/$locale/admin/translations'
    | '/$locale/admin/users'
    | '/$locale/events/create'
    | '/$locale/testimonies/create'
    | '/login/facebook/callback'
    | '/login/google/callback'
    | '/login/twitter/callback'
    | '/$locale/events/$id/edit'
    | '/$locale/testimonies/$id/edit'
    | '/$locale/events/$id/'
    | '/$locale/testimonies/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  LoginFacebookRoute: typeof LoginFacebookRouteWithChildren
  LoginGoogleRoute: typeof LoginGoogleRouteWithChildren
  LoginTwitterRoute: typeof LoginTwitterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/login/twitter': {
      id: '/login/twitter'
      path: '/login/twitter'
      fullPath: '/login/twitter'
      preLoaderRoute: typeof LoginTwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/google': {
      id: '/login/google'
      path: '/login/google'
      fullPath: '/login/google'
      preLoaderRoute: typeof LoginGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/facebook': {
      id: '/login/facebook'
      path: '/login/facebook'
      fullPath: '/login/facebook'
      preLoaderRoute: typeof LoginFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/testimonies': {
      id: '/$locale/testimonies'
      path: '/testimonies'
      fullPath: '/$locale/testimonies'
      preLoaderRoute: typeof LocaleTestimoniesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/roadmap': {
      id: '/$locale/roadmap'
      path: '/roadmap'
      fullPath: '/$locale/roadmap'
      preLoaderRoute: typeof LocaleRoadmapRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/profile': {
      id: '/$locale/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleProfileRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/events': {
      id: '/$locale/events'
      path: '/events'
      fullPath: '/$locale/events'
      preLoaderRoute: typeof LocaleEventsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dashboard': {
      id: '/$locale/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleDashboardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/login/twitter/callback': {
      id: '/login/twitter/callback'
      path: '/callback'
      fullPath: '/login/twitter/callback'
      preLoaderRoute: typeof LoginTwitterCallbackRouteImport
      parentRoute: typeof LoginTwitterRoute
    }
    '/login/google/callback': {
      id: '/login/google/callback'
      path: '/callback'
      fullPath: '/login/google/callback'
      preLoaderRoute: typeof LoginGoogleCallbackRouteImport
      parentRoute: typeof LoginGoogleRoute
    }
    '/login/facebook/callback': {
      id: '/login/facebook/callback'
      path: '/callback'
      fullPath: '/login/facebook/callback'
      preLoaderRoute: typeof LoginFacebookCallbackRouteImport
      parentRoute: typeof LoginFacebookRoute
    }
    '/$locale/testimonies/create': {
      id: '/$locale/testimonies/create'
      path: '/create'
      fullPath: '/$locale/testimonies/create'
      preLoaderRoute: typeof LocaleTestimoniesCreateRouteImport
      parentRoute: typeof LocaleTestimoniesRoute
    }
    '/$locale/events/create': {
      id: '/$locale/events/create'
      path: '/create'
      fullPath: '/$locale/events/create'
      preLoaderRoute: typeof LocaleEventsCreateRouteImport
      parentRoute: typeof LocaleEventsRoute
    }
    '/$locale/admin/users': {
      id: '/$locale/admin/users'
      path: '/users'
      fullPath: '/$locale/admin/users'
      preLoaderRoute: typeof LocaleAdminUsersRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/translations': {
      id: '/$locale/admin/translations'
      path: '/translations'
      fullPath: '/$locale/admin/translations'
      preLoaderRoute: typeof LocaleAdminTranslationsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/recommendations': {
      id: '/$locale/admin/recommendations'
      path: '/recommendations'
      fullPath: '/$locale/admin/recommendations'
      preLoaderRoute: typeof LocaleAdminRecommendationsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/moderation': {
      id: '/$locale/admin/moderation'
      path: '/moderation'
      fullPath: '/$locale/admin/moderation'
      preLoaderRoute: typeof LocaleAdminModerationRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/feedback': {
      id: '/$locale/admin/feedback'
      path: '/feedback'
      fullPath: '/$locale/admin/feedback'
      preLoaderRoute: typeof LocaleAdminFeedbackRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/courses': {
      id: '/$locale/admin/courses'
      path: '/courses'
      fullPath: '/$locale/admin/courses'
      preLoaderRoute: typeof LocaleAdminCoursesRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/testimonies/$id/': {
      id: '/$locale/testimonies/$id/'
      path: '/$id'
      fullPath: '/$locale/testimonies/$id/'
      preLoaderRoute: typeof LocaleTestimoniesIdIndexRouteImport
      parentRoute: typeof LocaleTestimoniesRoute
    }
    '/$locale/events/$id/': {
      id: '/$locale/events/$id/'
      path: '/$id'
      fullPath: '/$locale/events/$id/'
      preLoaderRoute: typeof LocaleEventsIdIndexRouteImport
      parentRoute: typeof LocaleEventsRoute
    }
    '/$locale/testimonies/$id/edit': {
      id: '/$locale/testimonies/$id/edit'
      path: '/$id/edit'
      fullPath: '/$locale/testimonies/$id/edit'
      preLoaderRoute: typeof LocaleTestimoniesIdEditRouteImport
      parentRoute: typeof LocaleTestimoniesRoute
    }
    '/$locale/events/$id/edit': {
      id: '/$locale/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/$locale/events/$id/edit'
      preLoaderRoute: typeof LocaleEventsIdEditRouteImport
      parentRoute: typeof LocaleEventsRoute
    }
  }
}

interface LocaleAdminRouteChildren {
  LocaleAdminCoursesRoute: typeof LocaleAdminCoursesRoute
  LocaleAdminFeedbackRoute: typeof LocaleAdminFeedbackRoute
  LocaleAdminModerationRoute: typeof LocaleAdminModerationRoute
  LocaleAdminRecommendationsRoute: typeof LocaleAdminRecommendationsRoute
  LocaleAdminTranslationsRoute: typeof LocaleAdminTranslationsRoute
  LocaleAdminUsersRoute: typeof LocaleAdminUsersRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminCoursesRoute: LocaleAdminCoursesRoute,
  LocaleAdminFeedbackRoute: LocaleAdminFeedbackRoute,
  LocaleAdminModerationRoute: LocaleAdminModerationRoute,
  LocaleAdminRecommendationsRoute: LocaleAdminRecommendationsRoute,
  LocaleAdminTranslationsRoute: LocaleAdminTranslationsRoute,
  LocaleAdminUsersRoute: LocaleAdminUsersRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleEventsRouteChildren {
  LocaleEventsCreateRoute: typeof LocaleEventsCreateRoute
  LocaleEventsIdEditRoute: typeof LocaleEventsIdEditRoute
  LocaleEventsIdIndexRoute: typeof LocaleEventsIdIndexRoute
}

const LocaleEventsRouteChildren: LocaleEventsRouteChildren = {
  LocaleEventsCreateRoute: LocaleEventsCreateRoute,
  LocaleEventsIdEditRoute: LocaleEventsIdEditRoute,
  LocaleEventsIdIndexRoute: LocaleEventsIdIndexRoute,
}

const LocaleEventsRouteWithChildren = LocaleEventsRoute._addFileChildren(
  LocaleEventsRouteChildren,
)

interface LocaleTestimoniesRouteChildren {
  LocaleTestimoniesCreateRoute: typeof LocaleTestimoniesCreateRoute
  LocaleTestimoniesIdEditRoute: typeof LocaleTestimoniesIdEditRoute
  LocaleTestimoniesIdIndexRoute: typeof LocaleTestimoniesIdIndexRoute
}

const LocaleTestimoniesRouteChildren: LocaleTestimoniesRouteChildren = {
  LocaleTestimoniesCreateRoute: LocaleTestimoniesCreateRoute,
  LocaleTestimoniesIdEditRoute: LocaleTestimoniesIdEditRoute,
  LocaleTestimoniesIdIndexRoute: LocaleTestimoniesIdIndexRoute,
}

const LocaleTestimoniesRouteWithChildren =
  LocaleTestimoniesRoute._addFileChildren(LocaleTestimoniesRouteChildren)

interface LocaleRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleDashboardRoute: typeof LocaleDashboardRoute
  LocaleEventsRoute: typeof LocaleEventsRouteWithChildren
  LocaleProfileRoute: typeof LocaleProfileRoute
  LocaleRoadmapRoute: typeof LocaleRoadmapRoute
  LocaleTestimoniesRoute: typeof LocaleTestimoniesRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleDashboardRoute: LocaleDashboardRoute,
  LocaleEventsRoute: LocaleEventsRouteWithChildren,
  LocaleProfileRoute: LocaleProfileRoute,
  LocaleRoadmapRoute: LocaleRoadmapRoute,
  LocaleTestimoniesRoute: LocaleTestimoniesRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface LoginFacebookRouteChildren {
  LoginFacebookCallbackRoute: typeof LoginFacebookCallbackRoute
}

const LoginFacebookRouteChildren: LoginFacebookRouteChildren = {
  LoginFacebookCallbackRoute: LoginFacebookCallbackRoute,
}

const LoginFacebookRouteWithChildren = LoginFacebookRoute._addFileChildren(
  LoginFacebookRouteChildren,
)

interface LoginGoogleRouteChildren {
  LoginGoogleCallbackRoute: typeof LoginGoogleCallbackRoute
}

const LoginGoogleRouteChildren: LoginGoogleRouteChildren = {
  LoginGoogleCallbackRoute: LoginGoogleCallbackRoute,
}

const LoginGoogleRouteWithChildren = LoginGoogleRoute._addFileChildren(
  LoginGoogleRouteChildren,
)

interface LoginTwitterRouteChildren {
  LoginTwitterCallbackRoute: typeof LoginTwitterCallbackRoute
}

const LoginTwitterRouteChildren: LoginTwitterRouteChildren = {
  LoginTwitterCallbackRoute: LoginTwitterCallbackRoute,
}

const LoginTwitterRouteWithChildren = LoginTwitterRoute._addFileChildren(
  LoginTwitterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  LoginFacebookRoute: LoginFacebookRouteWithChildren,
  LoginGoogleRoute: LoginGoogleRouteWithChildren,
  LoginTwitterRoute: LoginTwitterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
